
apiVersion: v1
kind: Service
metadata:
  namespace: quest
  name: accounts-intel
  labels:
    app: accs
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: accs
    tier: backend
  ports:
    - name: http
      port: 802
      targetPort: 8080
